### ISSUE TITLE
Simple self-contained report example that compiles without errors?

### ISSUE THREAD

**Issue by spth** [KWARC/LaTeX-proposal#52] opened 2022-05-20 12:15 UTC
Would it be possible to add a simple example for the final report to the documentation?

* It should compile without errors (I can get a .pdf from the current example, but that is due to batchmode, and thus errors being ignored).
* It should be self-contained, i.e. not depend on other files, such as a proposal.

**Comment by kohlhase** [comment] 2022-05-21 09:55
Thanks for the notification. I see that the whole package seems to have regressed. I will look into that.

**Comment by kohlhase** [comment] 2022-05-21 10:11
Acutally, the dfg proposal was fine, and formats fine for me (after I have formatted the file `../proposal/proposal.tex` to obtain the file `../proposal/proposal.pdata`, which is loaded to keep the metadata intact. 

This dependence on the proposal data is intended behavior (even though you say that you want a self-contained example). 
I will improve the error handling when the pdata file does not exist.

**Comment by kohlhase** [comment] 2022-05-21 10:40
better error messages established, closing with thanks.

**Closed as completed by kohlhase** 2022-05-21 10:40 UTC
